# Generated by Django 5.2.8 on 2025-12-02 22:06

from django.db import migrations, models


def set_existing_users_approved(apps, schema_editor):
    """Set all existing users to approved status"""
    CustomUser = apps.get_model('booking', 'CustomUser')
    CustomUser.objects.all().update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(set_existing_users_approved),
    ]
