# Generated by Codex on 2026-06-05

from django.db import migrations, models


def deactivate_upstairs_room_2(apps, schema_editor):
    Room = apps.get_model("booking", "Room")
    room_ids = []

    for room in Room.objects.select_related("floor"):
        room_name = " ".join(room.name.lower().split())
        floor_name = " ".join(room.floor.name.lower().split())

        if (
            floor_name == "upstairs"
            and room_name == "room 2"
        ) or room_name in {"upstairs room 2", "upstairs 2"}:
            room_ids.append(room.id)

    if room_ids:
        Room.objects.filter(id__in=room_ids).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(deactivate_upstairs_room_2, migrations.RunPython.noop),
    ]
