# Generated by Django 5.2.8 on 2025-12-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_customuser_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('camp', 'Camp')], db_index=True, default='regular', max_length=20),
        ),
    ]
