# Generated by Codex on 2026-06-05

from django.db import migrations


UPSTAIRS_FLOOR_NAMES = {
    "upstairs",
    "floor 2",
    "second floor",
    "2nd floor",
    "main building floor 2",
}

UPSTAIRS_ROOM_NAMES = {
    "room 2",
    "upstairs room 2",
    "upstairs 2",
}


def normalize(value):
    return " ".join(value.lower().split())


def deactivate_upstairs_room_2_aliases(apps, schema_editor):
    Room = apps.get_model("booking", "Room")
    room_ids = []

    for room in Room.objects.select_related("floor"):
        floor_name = normalize(room.floor.name)
        room_name = normalize(room.name)

        if room_name in UPSTAIRS_ROOM_NAMES and (
            floor_name in UPSTAIRS_FLOOR_NAMES or room_name != "room 2"
        ):
            room_ids.append(room.id)

    if room_ids:
        Room.objects.filter(id__in=room_ids).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_room_is_active_remove_upstairs_room_2"),
    ]

    operations = [
        migrations.RunPython(deactivate_upstairs_room_2_aliases, migrations.RunPython.noop),
    ]
